feat(BoemlyFormControl): Add Slider as InputType
treely/boemly pull request #161
Opened 2023-03-16 16:31 UTC by rschiffer

2023-03-20 09:04 UTC, lukasbals requested changes

2023-03-20 09:04 UTC, lukasbals commented on src/components/BoemlyFormControl/BoemlyFormControl.tsx
> +        return <Slider onChange={() => null} ariaLabel="slider" {...sliderProps} />;
Hmm, I don't like those "default values". But I'm not sure yet what's the best solution for this. Will think about it and comment later ....

2023-03-20 11:50 UTC, lukasbals commented on src/components/BoemlyFormControl/BoemlyFormControl.tsx
> +        return <Slider onChange={() => null} ariaLabel="slider" {...sliderProps} />;
```suggestion
      case 'Slider':
        return <Slider onChange={() => undefined} ariaLabel={label || 'slider'} {...sliderProps} />;
```

What about that? I can't find a better solution 🤔

2023-03-20 12:37 UTC, rschiffer commented on src/components/BoemlyFormControl/BoemlyFormControl.tsx
> +        return <Slider onChange={() => null} ariaLabel="slider" {...sliderProps} />;
Works for me 👍

2023-03-21 10:20 UTC, lukasbals approved these changes
Looks good to me! 🤓

2023-03-21 11:28 UTC, merged